/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'HOME': RouteRecordInfo<
      'HOME',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DNS': RouteRecordInfo<
      'DNS',
      '/dns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PRIVATE_DNS': RouteRecordInfo<
      'PRIVATE_DNS',
      '/dns/private-dns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ERROR_PRIVATE_DNS': RouteRecordInfo<
      'ERROR_PRIVATE_DNS',
      '/dns/private-dns/error-private-dns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'TURN_OFF_PRIVATE_DNS': RouteRecordInfo<
      'TURN_OFF_PRIVATE_DNS',
      '/dns/private-dns/turn-off-private-dns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ENGINE_ERROR': RouteRecordInfo<
      'ENGINE_ERROR',
      '/engine-error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'INTERNAL_AD': RouteRecordInfo<
      'INTERNAL_AD',
      '/internal-ad',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'FREE_SERVERS_DISRUPTIONS': RouteRecordInfo<
      'FREE_SERVERS_DISRUPTIONS',
      '/learn-more/free-servers-disruptions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PRIVACY_POLICY': RouteRecordInfo<
      'PRIVACY_POLICY',
      '/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PROMOTE_PREMIUM': RouteRecordInfo<
      'PROMOTE_PREMIUM',
      '/promote-premium',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PROTOCOLS': RouteRecordInfo<
      'PROTOCOLS',
      '/protocols',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'CLOAK_MODE': RouteRecordInfo<
      'CLOAK_MODE',
      '/protocols/cloak-mode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PURCHASE_SUBSCRIPTION': RouteRecordInfo<
      'PURCHASE_SUBSCRIPTION',
      '/purchase-subscription',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SERVERS': RouteRecordInfo<
      'SERVERS',
      '/servers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'EXTEND_SESSION': RouteRecordInfo<
      'EXTEND_SESSION',
      '/servers/extend-session',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SETTINGS': RouteRecordInfo<
      'SETTINGS',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ALWAYS_ON': RouteRecordInfo<
      'ALWAYS_ON',
      '/settings/always-on',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'KILL_SWITCH': RouteRecordInfo<
      'KILL_SWITCH',
      '/settings/kill-switch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LANGUAGE': RouteRecordInfo<
      'LANGUAGE',
      '/settings/language',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'NOTIFICATIONS': RouteRecordInfo<
      'NOTIFICATIONS',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'PROXIES': RouteRecordInfo<
      'PROXIES',
      '/settings/proxies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'QUICK_LAUNCH': RouteRecordInfo<
      'QUICK_LAUNCH',
      '/settings/quick-launch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_TUNNELING': RouteRecordInfo<
      'SPLIT_TUNNELING',
      '/split-tunneling',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_APPS': RouteRecordInfo<
      'SPLIT_APPS',
      '/split-tunneling/split-apps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_COUNTRIES': RouteRecordInfo<
      'SPLIT_COUNTRIES',
      '/split-tunneling/split-countries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_DNS': RouteRecordInfo<
      'SPLIT_DNS',
      '/split-tunneling/split-dns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_DOMAINS': RouteRecordInfo<
      'SPLIT_DOMAINS',
      '/split-tunneling/split-domains',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_IPS_VIA_APP': RouteRecordInfo<
      'SPLIT_IPS_VIA_APP',
      '/split-tunneling/split-ips-via-app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_IPS_VIA_DEVICE': RouteRecordInfo<
      'SPLIT_IPS_VIA_DEVICE',
      '/split-tunneling/split-ips-via-device',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_IPV6': RouteRecordInfo<
      'SPLIT_IPV6',
      '/split-tunneling/split-ipv6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SPLIT_LOCAL_NETWORK': RouteRecordInfo<
      'SPLIT_LOCAL_NETWORK',
      '/split-tunneling/split-local-network',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'STATISTICS': RouteRecordInfo<
      'STATISTICS',
      '/statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ACCOUNT': RouteRecordInfo<
      'ACCOUNT',
      '/user/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'HOME'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dns/index.vue': {
      routes:
        | 'DNS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dns/private-dns/index.vue': {
      routes:
        | 'PRIVATE_DNS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dns/private-dns/error-private-dns.vue': {
      routes:
        | 'ERROR_PRIVATE_DNS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dns/private-dns/turn-off-private-dns.vue': {
      routes:
        | 'TURN_OFF_PRIVATE_DNS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/engine-error.vue': {
      routes:
        | 'ENGINE_ERROR'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/internal-ad.vue': {
      routes:
        | 'INTERNAL_AD'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/learn-more/free-servers-disruptions.vue': {
      routes:
        | 'FREE_SERVERS_DISRUPTIONS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/privacy-policy.vue': {
      routes:
        | 'PRIVACY_POLICY'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/promote-premium.vue': {
      routes:
        | 'PROMOTE_PREMIUM'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/protocols/index.vue': {
      routes:
        | 'PROTOCOLS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/protocols/cloak-mode.vue': {
      routes:
        | 'CLOAK_MODE'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/purchase-subscription.vue': {
      routes:
        | 'PURCHASE_SUBSCRIPTION'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/servers/index.vue': {
      routes:
        | 'SERVERS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/servers/extend-session.vue': {
      routes:
        | 'EXTEND_SESSION'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | 'SETTINGS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/always-on.vue': {
      routes:
        | 'ALWAYS_ON'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/kill-switch.vue': {
      routes:
        | 'KILL_SWITCH'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/language.vue': {
      routes:
        | 'LANGUAGE'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | 'NOTIFICATIONS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/proxies.vue': {
      routes:
        | 'PROXIES'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/quick-launch.vue': {
      routes:
        | 'QUICK_LAUNCH'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/index.vue': {
      routes:
        | 'SPLIT_TUNNELING'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/split-apps.vue': {
      routes:
        | 'SPLIT_APPS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/split-countries.vue': {
      routes:
        | 'SPLIT_COUNTRIES'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/split-dns.vue': {
      routes:
        | 'SPLIT_DNS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/split-domains.vue': {
      routes:
        | 'SPLIT_DOMAINS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/split-ips-via-app.vue': {
      routes:
        | 'SPLIT_IPS_VIA_APP'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/split-ips-via-device.vue': {
      routes:
        | 'SPLIT_IPS_VIA_DEVICE'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/split-ipv6.vue': {
      routes:
        | 'SPLIT_IPV6'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/split-tunneling/split-local-network.vue': {
      routes:
        | 'SPLIT_LOCAL_NETWORK'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/statistics.vue': {
      routes:
        | 'STATISTICS'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/account.vue': {
      routes:
        | 'ACCOUNT'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
