/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'HOME': RouteRecordInfo<'HOME', '/', Record<never, never>, Record<never, never>>,
    'APP_FILTER': RouteRecordInfo<'APP_FILTER', '/app-filter', Record<never, never>, Record<never, never>>,
    'ERROR_PAGE': RouteRecordInfo<'ERROR_PAGE', '/error-page', Record<never, never>, Record<never, never>>,
    'PRIVACY_POLICY': RouteRecordInfo<'PRIVACY_POLICY', '/privacy-policy', Record<never, never>, Record<never, never>>,
    'PURCHASE_SUBSCRIPTION': RouteRecordInfo<'PURCHASE_SUBSCRIPTION', '/purchase-subscription', Record<never, never>, Record<never, never>>,
    'SERVERS': RouteRecordInfo<'SERVERS', '/servers', Record<never, never>, Record<never, never>>,
    'EXTEND_SESSION': RouteRecordInfo<'EXTEND_SESSION', '/servers/extend-session', Record<never, never>, Record<never, never>>,
    'PROMOTE_PREMIUM': RouteRecordInfo<'PROMOTE_PREMIUM', '/servers/promote-premium', Record<never, never>, Record<never, never>>,
    'SETTINGS': RouteRecordInfo<'SETTINGS', '/settings', Record<never, never>, Record<never, never>>,
    'FILTER_IP_BY_APP': RouteRecordInfo<'FILTER_IP_BY_APP', '/settings/filter-ip-by-app', Record<never, never>, Record<never, never>>,
    'FILTER_IP_BY_DEVICE': RouteRecordInfo<'FILTER_IP_BY_DEVICE', '/settings/filter-ip-by-device', Record<never, never>, Record<never, never>>,
    'LANGUAGES': RouteRecordInfo<'LANGUAGES', '/settings/languages', Record<never, never>, Record<never, never>>,
    'USAGE_STATISTICS': RouteRecordInfo<'USAGE_STATISTICS', '/usage-statistics', Record<never, never>, Record<never, never>>,
    'PREMIUM_USER': RouteRecordInfo<'PREMIUM_USER', '/user/premium-user', Record<never, never>, Record<never, never>>,
    'USER_ACCOUNT': RouteRecordInfo<'USER_ACCOUNT', '/user/user-account', Record<never, never>, Record<never, never>>,
  }
}
