/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'HOME': RouteRecordInfo<'HOME', '/', Record<never, never>, Record<never, never>>,
    'APP_FILTER': RouteRecordInfo<'APP_FILTER', '/app-filter', Record<never, never>, Record<never, never>>,
    'ERROR_PAGE': RouteRecordInfo<'ERROR_PAGE', '/error-page', Record<never, never>, Record<never, never>>,
    'INTERNAL_AD': RouteRecordInfo<'INTERNAL_AD', '/internal-ad', Record<never, never>, Record<never, never>>,
    'PRIVACY_POLICY': RouteRecordInfo<'PRIVACY_POLICY', '/privacy-policy', Record<never, never>, Record<never, never>>,
    'PURCHASE_SUBSCRIPTION': RouteRecordInfo<'PURCHASE_SUBSCRIPTION', '/purchase-subscription', Record<never, never>, Record<never, never>>,
    'SERVERS': RouteRecordInfo<'SERVERS', '/servers', Record<never, never>, Record<never, never>>,
    'EXTEND_SESSION': RouteRecordInfo<'EXTEND_SESSION', '/servers/extend-session', Record<never, never>, Record<never, never>>,
    'PROMOTE_PREMIUM': RouteRecordInfo<'PROMOTE_PREMIUM', '/servers/promote-premium', Record<never, never>, Record<never, never>>,
    'SETTINGS': RouteRecordInfo<'SETTINGS', '/settings', Record<never, never>, Record<never, never>>,
    'ALWAYS_ON': RouteRecordInfo<'ALWAYS_ON', '/settings/always-on', Record<never, never>, Record<never, never>>,
    'CLOAK_MODE': RouteRecordInfo<'CLOAK_MODE', '/settings/cloak-mode', Record<never, never>, Record<never, never>>,
    'DNS': RouteRecordInfo<'DNS', '/settings/dns', Record<never, never>, Record<never, never>>,
    'PRIVATE_DNS': RouteRecordInfo<'PRIVATE_DNS', '/settings/dns/private-dns', Record<never, never>, Record<never, never>>,
    'ERROR_PRIVATE_DNS': RouteRecordInfo<'ERROR_PRIVATE_DNS', '/settings/dns/private-dns/error-private-dns', Record<never, never>, Record<never, never>>,
    'TURN_OFF_PRIVATE_DNS': RouteRecordInfo<'TURN_OFF_PRIVATE_DNS', '/settings/dns/private-dns/turn-off-private-dns', Record<never, never>, Record<never, never>>,
    'FILTER_IP': RouteRecordInfo<'FILTER_IP', '/settings/filter-ip', Record<never, never>, Record<never, never>>,
    'FILTER_IPS_BY_APP': RouteRecordInfo<'FILTER_IPS_BY_APP', '/settings/filter-ip/filter-ips-by-app', Record<never, never>, Record<never, never>>,
    'FILTER_IPS_BY_DEVICE': RouteRecordInfo<'FILTER_IPS_BY_DEVICE', '/settings/filter-ip/filter-ips-by-device', Record<never, never>, Record<never, never>>,
    'KILL_SWITCH': RouteRecordInfo<'KILL_SWITCH', '/settings/kill-switch', Record<never, never>, Record<never, never>>,
    'LANGUAGE': RouteRecordInfo<'LANGUAGE', '/settings/language', Record<never, never>, Record<never, never>>,
    'NOTIFICATIONS': RouteRecordInfo<'NOTIFICATIONS', '/settings/notifications', Record<never, never>, Record<never, never>>,
    'PROTOCOLS': RouteRecordInfo<'PROTOCOLS', '/settings/protocols', Record<never, never>, Record<never, never>>,
    'QUICK_LAUNCH': RouteRecordInfo<'QUICK_LAUNCH', '/settings/quick-launch', Record<never, never>, Record<never, never>>,
    'STATISTICS': RouteRecordInfo<'STATISTICS', '/statistics', Record<never, never>, Record<never, never>>,
    'ACCOUNT': RouteRecordInfo<'ACCOUNT', '/user/account', Record<never, never>, Record<never, never>>,
    'PREMIUM_USER': RouteRecordInfo<'PREMIUM_USER', '/user/premium-user', Record<never, never>, Record<never, never>>,
  }
}
