/**
 * Loads the long-form documents in src/content/&lt;lang&gt;/ — the counterpart of locales/i18n.ts for
 * text too long to live in a resource file. Only src/content/en is hand-authored; every sibling
 * language folder is generated by vhtranslator's `docs` mode, and the build renders each file to
 * an HTML fragment (see build/markdown-content-plugin.ts).
 */
interface ContentModule {
  default: string;
  title: string;
}

export interface ContentDocument {
  /** The document title from the front matter; empty when it has none. */
  title: string;
  /** The rendered HTML fragment, ready for v-html. */
  html: string;
  /** The language actually loaded — the requested one, or 'en' when it had no translation. */
  languageCode: string;
}

/**
 * A glob WITHOUT `eager`, exactly as the locale bundles are loaded: the paths are known at build
 * time but each document stays in its own chunk, so a user downloads their own language only.
 */
const documentLoaders = import.meta.glob<ContentModule>('../content/*/*.md');

const SourceLanguage = 'en';

function pathOf(name: string, languageCode: string): string {
  return `../content/${languageCode}/${name}.md`;
}

/**
 * Loads one document in the requested language, falling back to English. The fallback is not
 * theoretical: a language whose translation failed verification is deliberately not written, so a
 * missing file is the normal way the translator reports "no trustworthy translation yet" — and
 * showing the English text beats showing nothing, especially on the consent screen.
 */
export async function loadContentDocument(name: string, languageCode: string): Promise<ContentDocument> {
  const resolvedLanguage = documentLoaders[pathOf(name, languageCode)] ? languageCode : SourceLanguage;

  const loader = documentLoaders[pathOf(name, resolvedLanguage)];
  if (!loader) throw new Error(`No content document '${name}' is shipped for '${SourceLanguage}'.`);

  const module = await loader();
  return { title: module.title, html: module.default, languageCode: resolvedLanguage };
}
