// Strict union of ALL theme color tokens used in your vuetify.ts
export type ThemeColorKey =
  | 'background' | 'surface' | 'on-background' | 'colored-bg-light' | 'colored-bg-dark' | 'app-bg'
  | 'rate-icon' | 'rate-dialog-border' | 'rate-dialog-thanks'
  | 'app-bar' | 'on-app-bar'
  | 'navigation-drawer' | 'navigation-drawer-header' | 'navigation-drawer-version'
  | 'home-app-bar'
  | 'home-bg-grad-1' | 'home-bg-grad-2'
  | 'connect-btn-disconnected-grad-1' | 'connect-btn-disconnected-grad-2' | 'connect-btn-connected'
  | 'on-connect-btn-disconnected' | 'on-connect-btn-connected'
  | 'count-down-normal' | 'count-down-alert' | 'count-down-warning'
  | 'go-premium-btn' | 'on-go-premium-btn'
  | 'promote-premium-border' | 'promote-premium-color-premium' | 'on-promote-premium-color-premium'
  | 'promote-premium-color-free' | 'on-promote-premium-color-free' | 'premium-features-icon'
  | 'premium-code-btn' | 'purchase-subscription-btn' | 'on-purchase-subscription-btn'
  | 'activate-code-btn' | 'on-activate-code-btn'
  | 'suppress-snackbar' | 'on-suppress-snackbar'
  | 'update-snackbar-alert' | 'update-snackbar-warning' | 'btn-on-update-snackbar'
  | 'connection-speed' | 'total-bandwidth'
  | 'expire-date-alert' | 'expire-date-warning'
  | 'config-btn-bg' | 'on-config-btn-bg'
  | 'active-server' | 'fastest-server' | 'active-server-chip' | 'on-active-server-chip'
  | 'expansion-panels-collapsed'
  | 'active-profile-radio' | 'inactive-profile-radio'
  | 'config-card-bg' | 'zebra-on-config-card-bg' | 'config-card-on-expansion-panel'
  | 'dialog-light' | 'on-dialog-light' | 'dialog-light-text'
  | 'dialog-dark' | 'on-dialog-dark' | 'dialog-dark-text'
  | 'grad-bg-container-bg'
  | 'tonal-icon-btn'
  | 'card-on-grad-bg' | 'on-card-on-grad-bg'
  | 'general-dialog' | 'on-general-dialog' | 'general-dialog-text'
  | 'dialog-alert' | 'on-dialog-alert' | 'dialog-alert-text' | 'dialog-alert-btn'
  | 'sample-ip-filter-bg' | 'sample-ip-filter-text'
  | 'btn-style-1' | 'on-btn-style-1'
  | 'btn-style-2' | 'on-btn-style-2'
  | 'btn-style-3' | 'on-btn-style-3'
  | 'btn-style-4'
  | 'btn-style-5' | 'on-btn-style-5'
  | 'btn-style-6' | 'on-btn-style-6'
  | 'btn-style-7'
  | 'switch-btn'
  | 'connection-circle-border' | 'connection-circle-shine'
  | 'active' | 'on-active' | 'highlight' | 'enable-premium' | 'disable-premium'
  | 'disconnect-warning' | 'on-disconnect-warning'
  | 'version-on-home-debug' | 'on-version-on-home-debug'
  | 'info' | 'on-info' | 'note' | 'on-note' | 'error' | 'warning' | 'on-warning'
  | 'scroll-track' | 'scroll-thumb' | 'scroll-thumb-hover'
  | 'skeleton-loader';

export type ThemeColorNames = Record<ThemeColorKey, string>;
