name: Publish Nugets

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
  
    env:
        BUILD_CONFIG: 'Release'
        PROJECT_NAME: 'nuget/VpnHood.AppLib.Assets.ClassicSpa'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Bump versions
      uses: SiqiLu/dotnet-bump-version@2.0.0
      with:
        version_files: "**/*.csproj"
        version_mask: 0.0.1.0
        version_overwrite: "*.*.*.0-preview"
        github_token: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore $PROJECT_NAME

    - name: Build Solution
      run: dotnet build $PROJECT_NAME --no-restore --configuration $BUILD_CONFIG

    - name: Pack All Projects
      run: dotnet pack $PROJECT_NAME --configuration $BUILD_CONFIG -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: Publish
      run: dotnet nuget push "**/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{secrets.NUGET_API_KEY}}
